name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 11:00 AM IST
  workflow_dispatch:      # Allows manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add log entry by 23f2004624@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date -u)" >> daily-log.txt
          git config --global user.name "Mukund"
          git config --global user.email "23f2004624@ds.study.iitm.ac.in"
          git pull origin main --rebase
          git add daily-log.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
          git push
